version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:4000"
    env_file: .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
